name: Deploy Bicep file
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deployment
      uses: azure/bicep-deploy@v2
      with:
        type: deployment
        operation: create
        name: Development
        location: westeurope
        scope: subscription
        subscription-id: db7ae7e3-3ce9-4854-9c79-6b022bfa2fc3
        template-file: ./bicep/main.bicep
    #    parameters-file: ./main.bicepparam
